# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Python_Project/dxf_gcode/dxf_to_gcode_ui_base.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dxf_to_gcode(object):
    def setupUi(self, dxf_to_gcode):
        dxf_to_gcode.setObjectName("dxf_to_gcode")
        dxf_to_gcode.resize(1111, 809)
        self.centralwidget = QtWidgets.QWidget(dxf_to_gcode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1111, 756))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.hl_0 = QtWidgets.QHBoxLayout()
        self.hl_0.setObjectName("hl_0")
        self.btn_import = QtWidgets.QPushButton(self.centralwidget)
        self.btn_import.setObjectName("btn_import")
        self.hl_0.addWidget(self.btn_import)
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setObjectName("btn_save")
        self.hl_0.addWidget(self.btn_save)
        self.btn_quit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quit.setObjectName("btn_quit")
        self.hl_0.addWidget(self.btn_quit)
        self.gridLayout.addLayout(self.hl_0, 2, 1, 1, 1)
        self.w_plot = QtWidgets.QWidget(self.centralwidget)
        self.w_plot.setObjectName("w_plot")
        self.gridLayout.addWidget(self.w_plot, 0, 0, 1, 1)
        self.vl_0 = QtWidgets.QVBoxLayout()
        self.vl_0.setObjectName("vl_0")
        self.tv = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tv.sizePolicy().hasHeightForWidth())
        self.tv.setSizePolicy(sizePolicy)
        self.tv.setMinimumSize(QtCore.QSize(150, 0))
        self.tv.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tv.setDragEnabled(True)
        self.tv.setDragDropOverwriteMode(True)
        self.tv.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.tv.setAlternatingRowColors(True)
        self.tv.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tv.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tv.setHeaderHidden(True)
        self.tv.setObjectName("tv")
        self.tv.headerItem().setText(0, "1")
        self.vl_0.addWidget(self.tv)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_offset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_offset.setObjectName("btn_offset")
        self.gridLayout_2.addWidget(self.btn_offset, 0, 1, 1, 1)
        self.btn_group = QtWidgets.QPushButton(self.centralwidget)
        self.btn_group.setObjectName("btn_group")
        self.gridLayout_2.addWidget(self.btn_group, 0, 0, 1, 1)
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setObjectName("btn_delete")
        self.gridLayout_2.addWidget(self.btn_delete, 1, 0, 1, 1)
        self.btn_export_gcode = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export_gcode.setObjectName("btn_export_gcode")
        self.gridLayout_2.addWidget(self.btn_export_gcode, 1, 1, 1, 1)
        self.vl_0.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.vl_0, 0, 1, 2, 1)
        self.w_console = QtWidgets.QWidget(self.centralwidget)
        self.w_console.setObjectName("w_console")
        self.gridLayout.addWidget(self.w_console, 1, 0, 2, 1)
        dxf_to_gcode.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dxf_to_gcode)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuExport_Gcode = QtWidgets.QMenu(self.menubar)
        self.menuExport_Gcode.setObjectName("menuExport_Gcode")
        self.menuGeometry = QtWidgets.QMenu(self.menubar)
        self.menuGeometry.setObjectName("menuGeometry")
        self.menuOffset = QtWidgets.QMenu(self.menuGeometry)
        self.menuOffset.setObjectName("menuOffset")
        self.menuMove = QtWidgets.QMenu(self.menuGeometry)
        self.menuMove.setObjectName("menuMove")
        dxf_to_gcode.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dxf_to_gcode)
        self.statusbar.setObjectName("statusbar")
        dxf_to_gcode.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(dxf_to_gcode)
        self.toolBar.setObjectName("toolBar")
        dxf_to_gcode.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionGroup = QtWidgets.QAction(dxf_to_gcode)
        self.actionGroup.setObjectName("actionGroup")
        self.actionSet_color = QtWidgets.QAction(dxf_to_gcode)
        self.actionSet_color.setObjectName("actionSet_color")
        self.actionDelete = QtWidgets.QAction(dxf_to_gcode)
        self.actionDelete.setObjectName("actionDelete")
        self.actionOpen = QtWidgets.QAction(dxf_to_gcode)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(dxf_to_gcode)
        self.actionSave.setObjectName("actionSave")
        self.actionUndo = QtWidgets.QAction(dxf_to_gcode)
        self.actionUndo.setObjectName("actionUndo")
        self.actionOptions = QtWidgets.QAction(dxf_to_gcode)
        self.actionOptions.setObjectName("actionOptions")
        self.actionImport = QtWidgets.QAction(dxf_to_gcode)
        self.actionImport.setObjectName("actionImport")
        self.actionDeleteG = QtWidgets.QAction(dxf_to_gcode)
        self.actionDeleteG.setObjectName("actionDeleteG")
        self.actionSet_color_2 = QtWidgets.QAction(dxf_to_gcode)
        self.actionSet_color_2.setObjectName("actionSet_color_2")
        self.actionModify = QtWidgets.QAction(dxf_to_gcode)
        self.actionModify.setObjectName("actionModify")
        self.actionImport_dxf = QtWidgets.QAction(dxf_to_gcode)
        self.actionImport_dxf.setObjectName("actionImport_dxf")
        self.actionOffsetOptions = QtWidgets.QAction(dxf_to_gcode)
        self.actionOffsetOptions.setObjectName("actionOffsetOptions")
        self.actionExport_Gcode = QtWidgets.QAction(dxf_to_gcode)
        self.actionExport_Gcode.setObjectName("actionExport_Gcode")
        self.actionSetOffsetThickness = QtWidgets.QAction(dxf_to_gcode)
        self.actionSetOffsetThickness.setObjectName("actionSetOffsetThickness")
        self.actionSetOffsetValue = QtWidgets.QAction(dxf_to_gcode)
        self.actionSetOffsetValue.setObjectName("actionSetOffsetValue")
        self.actionMoveSelection = QtWidgets.QAction(dxf_to_gcode)
        self.actionMoveSelection.setObjectName("actionMoveSelection")
        self.actionMoveAll = QtWidgets.QAction(dxf_to_gcode)
        self.actionMoveAll.setObjectName("actionMoveAll")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionImport_dxf)
        self.menuFile.addAction(self.actionExport_Gcode)
        self.menuEdit.addAction(self.actionUndo)
        self.menuExport_Gcode.addAction(self.actionOptions)
        self.menuExport_Gcode.addAction(self.actionImport)
        self.menuOffset.addAction(self.actionSetOffsetThickness)
        self.menuOffset.addAction(self.actionSetOffsetValue)
        self.menuMove.addAction(self.actionMoveSelection)
        self.menuMove.addAction(self.actionMoveAll)
        self.menuGeometry.addAction(self.actionSet_color)
        self.menuGeometry.addAction(self.actionGroup)
        self.menuGeometry.addAction(self.actionDeleteG)
        self.menuGeometry.addAction(self.actionModify)
        self.menuGeometry.addAction(self.menuMove.menuAction())
        self.menuGeometry.addAction(self.menuOffset.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuGeometry.menuAction())
        self.menubar.addAction(self.menuExport_Gcode.menuAction())

        self.retranslateUi(dxf_to_gcode)
        QtCore.QMetaObject.connectSlotsByName(dxf_to_gcode)

    def retranslateUi(self, dxf_to_gcode):
        _translate = QtCore.QCoreApplication.translate
        dxf_to_gcode.setWindowTitle(_translate("dxf_to_gcode", "DXF to Gcode Vectoriel Converter"))
        self.btn_import.setText(_translate("dxf_to_gcode", "Import"))
        self.btn_save.setText(_translate("dxf_to_gcode", "Save"))
        self.btn_quit.setText(_translate("dxf_to_gcode", "Quit"))
        self.btn_offset.setText(_translate("dxf_to_gcode", "Offset"))
        self.btn_group.setText(_translate("dxf_to_gcode", "Group"))
        self.btn_delete.setText(_translate("dxf_to_gcode", "Delete"))
        self.btn_export_gcode.setText(_translate("dxf_to_gcode", "Export Gcode"))
        self.menuFile.setTitle(_translate("dxf_to_gcode", "File"))
        self.menuEdit.setTitle(_translate("dxf_to_gcode", "Edit"))
        self.menuExport_Gcode.setTitle(_translate("dxf_to_gcode", "Gcode"))
        self.menuGeometry.setTitle(_translate("dxf_to_gcode", "Geometry"))
        self.menuOffset.setTitle(_translate("dxf_to_gcode", "Offset"))
        self.menuMove.setTitle(_translate("dxf_to_gcode", "Move"))
        self.toolBar.setWindowTitle(_translate("dxf_to_gcode", "toolBar"))
        self.actionGroup.setText(_translate("dxf_to_gcode", "Group"))
        self.actionSet_color.setText(_translate("dxf_to_gcode", "Set color"))
        self.actionDelete.setText(_translate("dxf_to_gcode", "Delete"))
        self.actionOpen.setText(_translate("dxf_to_gcode", "Open"))
        self.actionSave.setText(_translate("dxf_to_gcode", "Save"))
        self.actionUndo.setText(_translate("dxf_to_gcode", "Undo"))
        self.actionOptions.setText(_translate("dxf_to_gcode", "Options"))
        self.actionImport.setText(_translate("dxf_to_gcode", "Import"))
        self.actionDeleteG.setText(_translate("dxf_to_gcode", "Delete"))
        self.actionSet_color_2.setText(_translate("dxf_to_gcode", "Set color"))
        self.actionModify.setText(_translate("dxf_to_gcode", "Modify"))
        self.actionImport_dxf.setText(_translate("dxf_to_gcode", "Import dxf"))
        self.actionOffsetOptions.setText(_translate("dxf_to_gcode", "Options"))
        self.actionExport_Gcode.setText(_translate("dxf_to_gcode", "Export Gcode"))
        self.actionSetOffsetThickness.setText(_translate("dxf_to_gcode", "Set thickness"))
        self.actionSetOffsetValue.setText(_translate("dxf_to_gcode", "Set offset"))
        self.actionMoveSelection.setText(_translate("dxf_to_gcode", "Move selection"))
        self.actionMoveAll.setText(_translate("dxf_to_gcode", "Move all"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dxf_to_gcode = QtWidgets.QMainWindow()
    ui = Ui_dxf_to_gcode()
    ui.setupUi(dxf_to_gcode)
    dxf_to_gcode.show()
    sys.exit(app.exec_())
